name: Setup Vcpkg
description: Install a full vcpkg environment
inputs:
  vcpkgCache:
    description: Cache vcpkg installation
    required: false
    default: |
      ~/.cache/vcpkg
      ~/vcpkg
      ~/AppData/Local/vcpkg

runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      with:
        path: ${{ inputs.vcpkgCache }}
        key: ${{ runner.os }}
        restore-keys: ${{ runner.os }}

    - uses: aminya/setup-cpp@v1
      with:
        vcpkg: true

    - name: Export Vcpkg Path for Windows
      if: ${{ runner.os == 'Windows' }}
      shell: powershell
      run: |
        echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT"
        setx VCPKG_ROOT "%VCPKG_INSTALLATION_ROOT%"
        setx PATH "%VCPKG_INSTALLATION_ROOT%;%PATH%"
        echo "PATH=$env:PATH"

    - name: Export Vcpkg Path for Linux
      if: ${{ runner.os != 'Windows' }}
      shell: bash
      run: |
        echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT"
        echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV
        echo "PATH=$VCPKG_INSTALLATION_ROOT:$PATH" >> $GITHUB_ENV
        echo "PATH=$PATH"
