name: Setup Vcpkg
description: Install a full vcpkg environment
inputs:
  vcpkgCache:
    description: Cache vcpkg installation
    required: false
    default: |
      ~/.cache/vcpkg
      ~/vcpkg
      ~/AppData/Local/vcpkg

runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      with:
        path: ${{ inputs.vcpkgCache }}
        key: ${{ runner.os }}
        restore-keys: ${{ runner.os }}

    - uses: aminya/setup-cpp@v1
      with:
        vcpkg: true

    - name: Export Vcpkg Path for Windows
      if: ${{ runner.os == 'Windows' }}
      shell: powershell
      run: |
        $vcpkgCommand = Get-Command vcpkg
        echo "VCPKG_ROOT=$(Split-Path $vcpkgCommand.Source)"
        setx VCPKG_ROOT "$(Split-Path $vcpkgCommand.Source)"
        setx PATH "$(Split-Path $vcpkgCommand.Source);%PATH%"
        echo "PATH=$env:PATH"

    - name: Export Vcpkg Path for Linux
      if: ${{ runner.os != 'Windows' }}
      shell: bash
      run: |
        vcpkgPath=$(which vcpkg)
        echo "VCPKG_ROOT=$(dirname $vcpkgPath)"
        echo "VCPKG_ROOT=$(dirname $vcpkgPath)" >> $GITHUB_ENV
        echo "PATH=$(dirname $vcpkgPath):$PATH" >> $GITHUB_ENV
        echo "PATH=$PATH"
