name: CI

on:
  workflow_dispatch:

  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Set up python
        uses: actions/setup-python@v4

      - name: Run pre-commit on codebase
        uses: pre-commit/action@v3.0.0

      - name: Auto commit action
        uses: stefanzweifel/git-auto-commit-action@v4
        if: failure()
        with:
          commit_message: 'ci: auto fixes from pre-commit'
